import type { WikiPage, WikiSection } from '../site-data';
import type { ContentBlock } from './types';
import tables from './dry-lab-tables.json';

const p = (text: string): ContentBlock => ({ kind: 'paragraph', text });
const h = (text: string): ContentBlock => ({ kind: 'heading', text });
const eq = (label: string, text: string): ContentBlock => ({ kind: 'equation', label, text });
const code = (label: string, text: string): ContentBlock => ({ kind: 'code', label, text });
const fig = (name: string, alt: string, caption: string): ContentBlock => ({ kind: 'figure', src: `/figures/dry-lab/${name}.png`, alt, caption });
const table = (id: keyof typeof tables, caption: string, collapsed = false): ContentBlock => ({ kind: 'table', caption, ...tables[id], collapsed });
const customTable = (caption: string, columns: string[], rows: string[][]): ContentBlock => ({ kind: 'table', caption, columns, rows });
const links = (...entries: [string, string][]): ContentBlock => ({ kind: 'links', links: entries.map(([label, href]) => ({ label, href })) });
const section = (title: string, ...blocks: ContentBlock[]): WikiSection => ({ title, body: '', blocks });

export const dryLabNavigation = [
  ['Transcriptomics', '/transcriptomics'],
  ['Metabolomics', '/metabolomics'],
  ['Protein', '/protein'],
  ['Mathematical Modeling', '/model'],
  ['Hardware', '/hardware'],
] as const;

export const transcriptomics: WikiPage = {
  title: 'Transcriptomics', eyebrow: 'Dry Lab / Transcriptomics', status: 'team-draft',
  intro: 'LCYB was selected from its position at the lycopene-to-β-carotene branch. Public light-intensity data then show how carotenoid-pathway transcripts respond and rank transcription-factor homologs by their expression association with that pathway.',
  sections: [
    section('Data and comparison design',
      p('The project’s LCYB modeling target comes from pathway structure. GSE120965 provides published light-intensity expression evidence, while project-strain validation forms a separate experimental evidence layer.'),
      p('GSE120965 contains three light intensities—150, 600 and 1500 µmol photons m⁻² s⁻¹—with three biological replicates per condition. GEO provides Readcount and FPKM matrices together with a unigene FASTA file. FPKM values from all nine samples were used to explore light responses and expression patterns; the FASTA sequences were used for pathway and transcription-factor annotation. Readcounts were used for the published 600/150 comparison and for the nine-sample DESeq fit and variance-stabilizing transformation used in coexpression analysis.'),
      links(['GSE120965 · expression matrices and sequences', 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120965']),
      customTable('Light-intensity experiment', ['PPFD (µmol photons m⁻² s⁻¹)', 'Samples', 'Biological replicates', 'Condition'], [
        ['150','LL1, LL2, LL3','3','low'], ['600','ML1, ML2, ML3','3','medium'], ['1500','HL1, HL2, HL3','3','high'],
      ]),
      p('The three-condition analysis compares 600/150, 1500/150 and 1500/600. The comparison with the paper uses LL1–LL3 and ML1–ML3 only. In each label, the first condition is compared with the second. Count-based fold changes and differences in mean log expression retain the definitions of their respective statistical models.'),
    ),
    section('Expression filtering and sample structure',
      p('The original matrix contains 76,875 expression features. Keeping features with FPKM ≥ 1 in at least three samples leaves 36,411 features. This retains transcripts expressed mainly in one light-intensity group while reducing the contribution of consistently near-zero features.'),
      p('For sample-scale estimation, 0.5 was added to FPKM to give finite logarithms at zero. The geometric mean of each feature across nine samples defines a reference; the median ratio of a sample to that reference defines its scale factor. The pseudocount 0.5 is used only for estimating the scale factor. Normalized FPKM is the original FPKM divided by that factor.'),
      eq('Sample-scale correction', String.raw`\begin{aligned}G_g&=\exp\!\left(\frac{1}{9}\sum_j\ln(F_{gj}+0.5)\right)\\s_j&=\operatorname{median}_g\!\left(\frac{F_{gj}+0.5}{G_g}\right)\\x_{gj}&=\log_2\!\left(\frac{F_{gj}}{s_j}+1\right)\end{aligned}`),
      p('Here F_gj is FPKM for feature g in sample j, s_j is the sample-scale factor, and x_gj is the value used for exploratory tests and plots. This adds a sample-composition correction to the uploaded FPKM before modeling log-expression variance.'),
      customTable('Sample-scale factors', ['Sample', 'Factor'], [['LL1','1.0712'],['LL2','1.0566'],['LL3','1.0034'],['ML1','1.0658'],['ML2','1.1239'],['ML3','1.0694'],['HL1','0.9310'],['HL2','0.8982'],['HL3','0.9307']]),
      p('The factors range from 0.8982 to 1.1239. Expression distributions were inspected after normalization. PCA used the 5,000 retained features with the highest variance, centered each feature, and preserved the differences in feature variance. PC1 and PC2 explain 35.45% and 14.96% of variance, respectively.'),
      fig('06_expression_qc','Sample-scale factors, normalized expression distributions and PCA for nine biological samples.', 'Figure 1. A: median-of-ratios scale factors; the dashed line marks 1. B: distributions of log₂(FPKMₙ + 1), with quartile boxes, median lines and whiskers extending to observations within 1.5 interquartile ranges. C: PCA, with one point per biological sample. PPFD is in µmol photons m⁻² s⁻¹. The axis percentages give explained variance.'),
      p('The sample structure supports condition-wise comparisons. Variation among replicates enters the downstream variance estimate.'),
      code('Expression filtering and transformation', 'expressed = (fpkm >= 1.0).sum(axis=1) >= 3\nfiltered = fpkm.loc[expressed]\nsize_factors = pd.Series(\n    median_of_ratios_factors(filtered.to_numpy() + 0.5),\n    index=filtered.columns,\n)\nlog_matrix = np.log2(filtered.div(size_factors, axis=1) + 1.0)'),
    ),
    section('Differential expression',
      p('Each exploratory comparison uses two groups of three samples. For every feature, the difference between mean log expression, the within-group residual sum of squares and a residual variance with four degrees of freedom were calculated. Empirical Bayes estimation supplies a prior variance s₀² and prior degrees of freedom d₀, shrinking individual variances toward this prior.'),
      eq('Moderated t statistic', String.raw`\begin{aligned}\Delta_g&=\bar{x}_{g,a}-\bar{x}_{g,b}\\s^2_{g,\mathrm{post}}&=\frac{d_0s_0^2+4s_g^2}{d_0+4}\\t_g&=\frac{\Delta_g}{\sqrt{s^2_{g,\mathrm{post}}(1/3+1/3)}}\end{aligned}`),
      p('Two-sided P values use a t distribution with d₀ + 4 degrees of freedom. Priors were fitted separately for the three comparisons, giving d₀ ≈ 1.4817, 1.4344 and 1.4592. Benjamini–Hochberg adjustment was applied within each comparison across all tested features. The exploratory code column log2FC stores Δ_g, the difference in mean log₂(normalized FPKM + 1); the +1 transformation affects fold interpretation at low expression.'),
      customTable('Exploratory differential-expression counts: FDR < 0.05 and |Δ_g| ≥ 1', ['Comparison', 'Upregulated', 'Downregulated', 'Total'], [['600/150','1,990','1,022','3,012'],['1500/150','2,088','1,789','3,877'],['1500/600','4,384','5,183','9,567']]),
      p('The union contains 11,583 features. The counting unit is a Trinity expression feature; several transcripts can correspond to one gene. Individual expression patterns and functional annotations provide the basis for subsequent candidate ranking.'),
      fig('07_differential_expression','Three volcano plots with identical axes for the light-intensity comparisons.', 'Figure 2. Each point is a tested feature. The x-axis is the difference in mean log expression; the y-axis is −log₁₀(FDR). Rose and blue mark upregulated and downregulated features meeting both thresholds. Horizontal and vertical lines indicate FDR = 0.05 and Δ = ±1. CRTISO has Δ = +4.0265 and FDR = 0.000997 in 1500/600.'),
      p('The annotated CRTISO transcript increases in the high-light group, connecting the global response to a specific carotenoid-pathway transcript.'),
    ),
    section('Light-response modules',
      p('For the 11,583 differential features, mean log expression was calculated in each of the three conditions and standardized within each feature. The population standard deviation (ddof = 0) was used. Features with nonzero between-condition standard deviation entered shape clustering.'),
      eq('Within-feature standardization', String.raw`\begin{aligned}\mathbf a_g&=(\bar x_{g,150},\bar x_{g,600},\bar x_{g,1500})\\z_{g,c}&=\frac{a_{g,c}-\operatorname{mean}(\mathbf a_g)}{\operatorname{sd}(\mathbf a_g)}\end{aligned}`),
      p('K-means compared k = 4–8 using k-means++ initialization, Euclidean distance, 40 initializations and at most 200 iterations per fit. Silhouette scores were calculated on the same 3,000-feature subsample. The random seed for model selection and bootstrap analyses was 20260826. The scores for k = 4, 5, 6, 7 and 8 were 0.5273, 0.5489, 0.5303, 0.5160 and 0.5162. Module labels were reordered by centroid shape after selecting k = 5.'),
      fig('08_response_modules','Five light-response module profiles and silhouette scores for choosing k.', 'Figure 3. A–E: average member Z-scores, with shaded 10th–90th percentiles of the member distribution. The x-axis contains three measured light intensities; lines connect these discrete conditions. F: silhouette scores across the tested k values.'),
      customTable('Selected response modules', ['Module', 'Features', 'Centroid expression order'], [['M1','991','150 > 600 > 1500'],['M2','1,578','600 > 1500 > 150'],['M3','4,023','600 > 150 > 1500'],['M4','1,708','1500 > 600 > 150'],['M5','3,283','1500 > 150 > 600']]),
      p('Module annotation used Bardawil reference proteins. All uploaded transcripts were aligned with DIAMOND blastx and filtered at E-value ≤ 10⁻⁵, identity ≥ 30% and query coverage ≥ 30%. Query coverage was 100 × (|qend − qstart| + 1) / qlen on either strand. In total, 31,869 transcripts matched 10,752 reference proteins; 14,676 alignments were on the reverse strand. The expressed enrichment background contained 9,906 reference proteins.'),
      p('Reference proteins were the enrichment counting unit. Each protein was assigned to the module of its most highly expressed responsive transcript. Hypergeometric tests were performed for 436 Pfam families having at least five background members, with all 436 P values adjusted together within each module and P = 1 for zero overlap. Of 2,180 module–family tests, 33 reached FDR < 0.05: 2, 1, 27, 2 and 1 in M1–M5. These modules describe response shapes; pathway annotation identifies the enzymes represented among those responses.'),
      links(['DIAMOND alignment fields','https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options'],['Benjamini–Hochberg adjustment','https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.false_discovery_control.html']),
    ),
    section('Carotenoid-pathway annotation',
      p('Trinity identifiers were annotated through protein homology. Primary-hit names identified carotenoid-pathway enzymes, and differential expression retained light-responsive transcripts. Li et al. (2019) report the 600/150 comparison from the same dataset and provide the pathway list used for comparison.'),
      links(['Li et al., 2019 · Phycological Research','https://doi.org/10.1111/pre.12379'],['Swiss-Prot release 2018_08','https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2018_08/knowledgebase/'],['UniSave entry history','https://www.uniprot.org/help/entry_history']),
      p('Reference proteins combined the official Swiss-Prot 2018_08 archive with historical Dunaliella entries restored through UniSave. The paper submission date, 12 October 2018, defined the time boundary. A search by genus taxid 3044 and creation date recovered 480 early entries still retrievable today; each was restored to its last available version on or before 11 October 2018, retaining historical names and sequences. The archive was checked against the publisher’s MD5, and historical records retained version identifiers, original text and SHA-256 checksums. Deleted UniProt records and the paper’s original Nr database remain outside this reconstructed reference set.'),
      p('All 76,875 uploaded Trinity sequences entered DIAMOND 2.2.5 blastx. Each database used sensitive mode, E-value ≤ 10⁻⁵, identity ≥ 20%, reference coverage ≥ 15% and at most ten targets per query. Hits were merged and a primary hit selected by descending bit score, then E-value and reference identifier. Primary-hit names identified PSY, PDS, ZDS, LCYB, CBR, carotene globule protein and D27. Both historical names “phytoene desaturase” and “15-cis-phytoene desaturase” were classified as PDS. Pathway annotations from weaker hits were retained in the annotation audit.'),
      p('These broad thresholds admit partial and more distant homologs for comparison with the published pathway list. TF annotation uses E-value < 10⁻⁵ and identity ≥ 30%, with reference and transcript coverage recorded for each match.'),
      h('Count-based pathway selection'),
      p('The paper and GEO sample-processing record specify DESeq 1.10.1, Benjamini–Hochberg adjustment and padj < 0.05. The uploaded Readcounts were reanalyzed using LL1–LL3 and ML1–ML3, retaining all 76,875 features. The six columns contain 135,644 fractional counts. R round was used to round to the nearest integer, with ties to even and a maximum change of 0.5 per count. This is an explicit recalculation setting because the publication does not describe fractional-count conversion.'),
      links(['GEO sample-processing record','https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3423032']),
      p('DESeq estimateSizeFactors supplied count-scale factors; estimateDispersions used the version defaults pooled, maximum and parametric; nbinomTest compared 600/150. The analysis yielded 9,375 differential features at padj < 0.05, compared with 9,374 reported in the paper. DESeq was fixed to archived version 1.10.1. The publication’s original database version, dispersion options and Table 2 inclusion rule require the original analysis records for exact matching.'),
      p('The six-sample count comparison and the nine-sample FPKM exploration use their own inputs, scale factors and variance models.'),
    ),
    section('Pathway results and published genes',
      p('The paper’s Table 2 lists 16 carotenoid-related Trinity transcripts for the 600/150 comparison. Historical protein annotation and the count-based DESeq analysis recover all 16. The table below follows those published identifiers in their original order.'),
      eq('Count-based fold change', String.raw`\mathrm{fold}_{g,600/150}=\frac{\operatorname{mean}_{j\in ML}(C_{gj}/s_j^{\mathrm{count}})}{\operatorname{mean}_{j\in LL}(C_{gj}/s_j^{\mathrm{count}})}`),
      p('C denotes rounded counts. Size factors use features positive in all six samples. Fold changes and adjusted P values come from the same DESeq fit. All 16 published identifiers reach padj < 0.05 with matching directions. Pearson r between the two log₂-fold columns is 0.999996; median and maximum absolute differences are 0.001946 and 0.010124. For LCYB Cluster-5009.34218, recalculated fold = 1.46387 and padj = 1.12742 × 10⁻¹⁰, compared with published values of 1.46 and 1.13 × 10⁻¹⁰.'),
      fig('01_gene_recovery','Published versus recalculated fold changes for the 16 shared Trinity identifiers.', 'Figure 4. A: published (open) and recalculated (filled) log₂-fold changes by identifier. Labels abbreviate the Cluster-5009. prefix. B: the same values plotted against each other, with y = x as a dashed reference. CGP denotes carotene globule protein. The displayed identifiers are the 16 shared with the published Table 2.'),
      table('RECOVERY','Published Table 2 and DESeq recalculation'),
      p('PSY, both LCYB transcripts, and the listed CBR, CGP and D27 transcripts increase in 600/150, while two PDS and one ZDS transcript decrease. Different positions in the carotenoid pathway respond in different directions.'),
      table('CANDIDATES','DESeq expression changes for the 16 published pathway transcripts',true),
      p('Trinity transcripts remain the expression-analysis unit, while protein alignment supplies functional evidence. Reference versions affect primary-hit names: historical annotation assigns CGP, CGP and PDS to Cluster-5009.18393, Cluster-5009.25866 and Cluster-5009.39420, respectively. The published-gene comparison uses the historical references and primary-hit rule described above.'),
      h('LCYB pathway role and light response'),
      p('LCYB (lycopene β-cyclase) catalyzes lycopene cyclization into the β-carotene branch, connecting the lycopene precursor pool to β-carotene and its downstream products. This pathway position makes LCYB the project’s regulatory and modeling target.'),
      p('In the GSE120965 600/150 comparison, both LCYB expression features increase significantly: Cluster-5009.34218 increases 1.46-fold (padj = 1.13 × 10⁻¹⁰), while Cluster-5009.36796 increases 3.29-fold (padj = 3.57 × 10⁻⁶). Cluster-5009.34218 follows the three-condition order 600 > 1500 > 150 and is assigned to response module M2. These results establish a significant transcriptional response of LCYB to light intensity, with its highest observed transcript level at the medium-light condition. The kinetic model carries this expression-layer response to β-carotene formation, and pigment measurements determine the product-level effect.'),
    ),
    section('Transcription-factor annotation and ranking',
      h('Pathway references and expression background'),
      p('Pathway references were assembled from PSY, PDS, ZDS, CRTISO, LCYB, LCYE and BCH annotations. Historical primary-hit annotations and enzyme-reference alignments were merged by Trinity identifier. Transcripts required usable expression data and padj < 0.05 in at least one light comparison. Thirteen references cover six enzyme classes; BCH did not meet this differential-expression criterion.'),
      customTable('Thirteen pathway references; identifiers share the Cluster-5009. prefix', ['Enzyme','Identifier suffixes'], [['CRTISO','33436'],['LCYB','34218, 36796'],['LCYE','32344'],['PDS','31297, 35653, 39420, 39826'],['PSY','23903, 45875'],['ZDS','11812, 34471, 6157']]),
      p('For this analysis, all nine Readcount columns were rounded with R round, normalized with DESeq 1.10.1 and fitted across LL, ML and HL with pooled, maximum, parametric dispersion estimation. All three pairwise tests use this nine-sample model and BH adjustment. The expression matrix uses getVarianceStabilizedData. The earlier FPKM ≥ 1 in at least three samples rule defines the expressed background; removing nonfinite and constant values leaves 36,411 transcripts. The six-sample fit remains specific to the published comparison.'),
      h('TF homologs'),
      p('All assembled transcripts were aligned against PlantTFDB Dunaliella salina proteins with DIAMOND blastx in sensitive mode, retaining targets with E-value < 10⁻⁵. Local matches required identity ≥ 30%. The strongest hit was selected by bit score, E-value and reference identifier; tied strongest hits involving several families retain all family names. This yielded 505 TF-homologous transcripts, of which 333 had usable expression data.'),
      links(['PlantTFDB reference proteins','https://planttfdb.gao-lab.org/']),
      p('Family labels describe reference-protein homology. Alignment length, identity, reference coverage and transcript coverage remain attached to each record, together with the reference CDS and protein identifiers. Multiple expressed fragments matching one protein remain separate ranked transcript features.'),
      h('Joint pathway coexpression'),
      p('The calculation follows the Mutual Rank definition and multi-reference logit aggregation described by ATTED-II. MutRank provides an example of combining coexpression retrieval with differential expression, functional annotation and domain evidence. Here, the rankings are calculated from the nine-sample expression matrix.'),
      links(['ATTED-II Mutual Rank','https://atted.jp/static/help/mr.shtml'],['ATTED-II multi-reference aggregation','https://doi.org/10.1093/pcp/pcx191'],['MutRank','https://doi.org/10.7717/peerj.10264']),
      p('Pearson correlation was calculated for every candidate–reference pair. Both directional ranks were calculated against the entire expressed background, excluding self-comparisons, with correlations ranked from highest to lowest and ties assigned average ranks. Mutual Rank is the geometric mean of the two directional ranks.'),
      eq('Mutual Rank and pathway aggregation', String.raw`\begin{aligned}MR_{ij}&=\sqrt{R_{i\to j}R_{j\to i}}\\S_i&=\sum_jw_j\ln\!\left(\frac{MR_{ij}}{N-MR_{ij}}\right)\\MR_i^*&=\frac{N}{1+\exp(-S_i)}\end{aligned}`),
      p('N is the expressed-background size. Each enzyme class receives equal total weight, split equally among its reference transcripts. Smaller integrated MR indicates a stronger same-direction association with the reference set. Candidates are sorted by increasing integrated MR, with exact ties broken by identifier. Family labels do not enter the score. Inverse integrated MR uses the opposite correlation order and is reported separately. Correlation and MR are dimensionless. Coexpression supplies candidate priority; binding and functional evidence determine promoter interaction and regulatory direction.'),
      h('Ranked transcripts'),
      p('C2H2 homolog Cluster-5009.32526 ranks first (integrated MR 9996.9), C2H2 homolog Cluster-5009.43049 second (10299.5), and NF-YC homolog Cluster-5009.41188 third (10828.8). Across nine leave-one-sample-out recalculations, their rank ranges are 1–2, 1–4 and 1–4. The first two match the same reference protein with reference coverage of 11.55% and 7.87%, respectively.'),
      p('The pathway enzymes have different light-response profiles. Correlations of the leading candidates with individual references include both positive and negative values. The integrated MR summarizes association with the whole reference set; sequence coverage accompanies the expression ranking.'),
      table('TF_RANKING','All 333 TF-homologous transcripts, ordered by integrated MR',true),
      p('Inverse rank is calculated from reverse correlation ranks using the same MR and weighting rules. Lower inverse ranks indicate stronger opposite-direction coexpression. Reference coverage is the percentage of the reference protein spanned by the local alignment.'),
      p('The highest joint ranks belong to C2H2 and NF-YC homologous fragments. Their ranks prioritize follow-up, while promoter binding and regulatory direction remain to be measured. The full annotation table retains every reference-family label alongside its alignment coverage.'),
    ),
  ],
};

export const modeling: WikiPage = {
  title: 'Mathematical Modeling', eyebrow: 'Dry Lab / Model', status: 'team-draft',
  intro: 'The model defines how a regulatory factor can alter LCYB transcription and propagate that change to β-carotene. It is a five-state, dimensional mechanism whose numerical output is generated from explicit project measurements.',
  sections: [
    section('Modeling question',
      p('LCYB catalyzes the conversion of lycopene to the β-carotene branch. The modeling question is therefore how a change in a regulatory factor reaches LCYB transcription, active enzyme and the β-carotene pool.'),
      p('The core model stops at β-carotene. Product-specific downstream kinetics remain in the metabolomics workstream, where their own enzyme parameters and measurements can be used.'),
      fig('14_regulatory_model','Five-state regulatory model linking an active regulatory factor, promoter occupancy, LCYB transcript, active LCYB and beta-carotene.', 'Figure 1. The five dynamic states are active regulatory factor T, LCYB transcript m, active LCYB E, lycopene L and β-carotene B. Promoter occupancy θ and the two reaction rates are algebraic functions. Colors distinguish regulatory, expression and metabolic layers.'),
    ),
    section('Promoter occupancy and transcription',
      p('A one-site equilibrium model connects active regulatory-factor concentration T and the dissociation constant Kd to promoter occupancy θ. Transcription is the occupancy-weighted average of the unbound and bound promoter rates.'),
      links(['Bintu et al. · promoter occupancy models','https://pubmed.ncbi.nlm.nih.gov/15797194/'],['Published D. bardawil lcyb promoter · KX218393','https://pubmed.ncbi.nlm.nih.gov/27657551/']),
      eq('Promoter input', String.raw`\theta=\frac{T}{K_d+T},\qquad u_{\mathrm{LCYB}}=u_{\mathrm{unbound}}(1-\theta)+u_{\mathrm{bound}}\theta`),
      p('When u_bound is larger than u_unbound, binding activates LCYB transcription; the reverse ordering represents repression. Regulator production, degradation and growth dilution determine T, while Kd describes binding affinity.'),
    ),
    section('Five differential equations',
      eq('Regulatory LCYB model', String.raw`\begin{aligned}
\frac{dT}{dt}&=s_T-(\delta_T+\mu)T\\
\frac{dm}{dt}&=u_{\mathrm{LCYB}}-(\delta_m+\mu)m\\
\frac{dE}{dt}&=k_{\mathrm{tl}}m-(\delta_E+\mu)E\\
\frac{dL}{dt}&=v_{\mathrm{supply}}-v_{\mathrm{LCYB}}-(k_L+\mu)L\\
\frac{dB}{dt}&=v_{\mathrm{LCYB}}-v_{\mathrm{out}}-(k_B+\mu)B
\end{aligned}`),
      eq('Metabolic rates', String.raw`v_{\mathrm{LCYB}}=q_{\mathrm{LCYB}}E\frac{L}{K_{m,\mathrm{LCYB}}+L},\qquad v_{\mathrm{out}}=V_{\mathrm{out}}\frac{B}{K_{m,\mathrm{out}}+B}`),
      customTable('State variables; time is measured in days', ['State','Quantity','Unit'], [
        ['T','Active regulatory factor','µmol L⁻¹'],
        ['m','LCYB transcript','nmol transcript L⁻¹'],
        ['E','Active LCYB','mg L⁻¹'],
        ['L','Lycopene','µmol L⁻¹'],
        ['B','β-carotene','µmol L⁻¹'],
      ]),
      p('Every right-hand side has the unit of its state per day. The caller supplies every biological parameter and initial value; the solver validates finiteness, nonnegativity and positive binding or Michaelis constants.'),
    ),
    section('Evidence and parameter status',
      p('Lan et al. measured LCYB overexpression, LCYB light responses and pigment content in D. salina. Each observation is retained with its original experimental comparison as evidence for the LCYB-to-β-carotene link; complete regulatory calibration uses a matched project time course.'),
      p('Mialoundama et al. measured recombinant pepper LCYB activity and an apparent lycopene Km. These values can define a cross-species prior range for q_LCYB and Km,LCYB. Project-specific regulator concentration, Kd, bound and unbound transcription rates, degradation rates, substrate supply and β-carotene removal remain model inputs to be measured.'),
      links(['Lan et al., 2022','https://doi.org/10.4014/jmb.2208.08044'],['Mialoundama et al., 2010','https://doi.org/10.1104/pp.110.155440']),
      customTable('Parameter evidence and units', ['Parameter','Meaning','Unit','Source'], [
        ['sT','Regulatory-factor production','µmol L⁻¹ d⁻¹','Project measurement'],
        ['δT','Regulatory-factor degradation','d⁻¹','Decay experiment or half-life'],
        ['Kd','Regulator–promoter dissociation constant','µmol L⁻¹','Binding experiment'],
        ['uunbound, ubound','Unbound and bound promoter transcription','nmol transcript L⁻¹ d⁻¹','Promoter reporter experiment'],
        ['δm','LCYB RNA degradation','d⁻¹','RNA half-life'],
        ['ktl','Active-enzyme formation per transcript','mg nmol⁻¹ d⁻¹','Protein abundance and translation rate'],
        ['δE','Active-LCYB degradation','d⁻¹','Protein half-life'],
        ['vsupply','Lycopene supply','µmol L⁻¹ d⁻¹','Metabolite time course or flux estimate'],
        ['qLCYB','Maximum rate per active LCYB','µmol mg⁻¹ d⁻¹','Dunaliella assay; plant LCYB prior range'],
        ['Km,LCYB','LCYB Michaelis constant for lycopene','µmol L⁻¹','Enzyme assay'],
        ['kL, kB','First-order pool losses','d⁻¹','Metabolite time course'],
        ['Vout, Km,out','β-carotene outflow capacity and constant','µmol L⁻¹ d⁻¹; µmol L⁻¹','Metabolomics workstream'],
        ['μ','Growth dilution','d⁻¹','Growth curve'],
      ]),
    ),
    section('What the model establishes',
      p('The equations specify the complete causal route requested for design: regulator production and stability change T; T and Kd determine promoter occupancy; occupancy changes LCYB transcription; translation changes active LCYB; LCYB then changes the lycopene-to-β-carotene flux.'),
      eq('Steady-state regulatory chain', String.raw`T^*=\frac{s_T}{\delta_T+\mu},\quad m^*=\frac{u_{\mathrm{LCYB}}(T^*)}{\delta_m+\mu},\quad E^*=\frac{k_{\mathrm{tl}}m^*}{\delta_E+\mu}`),
      p('With a stated parameter set, the implementation returns conditional trajectories for T, m, E, L and B and compares defined regulator variants. A matched project time course supplies the parameter set for an absolute project-yield prediction.'),
      fig('15_regulatory_response','Promoter occupancy and steady-state transfer from regulatory input to LCYB transcript and active enzyme.', 'Figure 2. A: promoter occupancy as a function of T/Kd; occupancy is 50% when T = Kd. B: the bound-to-unbound transcription ratio and T/Kd jointly determine the steady-state expression transfer. Color gives m*/m*unbound = E*/E*unbound; values above 1 represent activation and values below 1 represent repression. Both axes are parameter ratios fixed by the equations, while absolute trajectories use the measured parameters listed above.'),
      h('Quantitative findings'),
      p('Promoter occupancy rises from 10% to 90% as T/Kd rises from 1/9 to 9, an 81-fold span in effective regulator concentration relative to binding affinity. Half occupancy occurs at T = Kd. Writing r = u_bound/u_unbound, the steady-state LCYB transcript and active-enzyme fold relative to an unbound promoter is 1 + (r − 1)θ. At half occupancy this becomes (1 + r)/2: 1.50-fold for r = 2, 2.50-fold for r = 4, and 0.75-fold for r = 0.5. At T = 10Kd, where occupancy is 90.9%, the corresponding folds are 1.91, 3.73 and 0.55.'),
      p('The largest occupancy response occurs around T ≈ Kd. In the saturated T ≫ Kd regime, expression approaches the ceiling or floor set by r. With lycopene and enzyme-kinetic parameters held fixed, the instantaneous LCYB flux changes in the same proportion as active LCYB; the absolute β-carotene pool additionally depends on substrate supply, Michaelis constants, downstream outflow and loss.'),
      eq('Core implementation', String.raw`\begin{aligned}
\theta&=\frac{T}{K_d+T}\\
u_{\mathrm{LCYB}}&=u_{\mathrm{unbound}}(1-\theta)+u_{\mathrm{bound}}\theta\\
v_{\mathrm{LCYB}}&=q_{\mathrm{LCYB}}E\frac{L}{K_{m,\mathrm{LCYB}}+L}\\[4pt]
\frac{dT}{dt}&=s_T-(\delta_T+\mu)T\\
\frac{dm}{dt}&=u_{\mathrm{LCYB}}-(\delta_m+\mu)m\\
\frac{dE}{dt}&=k_{\mathrm{tl}}m-(\delta_E+\mu)E\\
\frac{dL}{dt}&=v_{\mathrm{supply}}-v_{\mathrm{LCYB}}-(k_L+\mu)L\\
\frac{dB}{dt}&=v_{\mathrm{LCYB}}-v_{\mathrm{out}}-(k_B+\mu)B
\end{aligned}`),
    ),
    section('Interface with metabolomics',
      p('The downstream metabolomics model begins at the β-carotene input flux. The interface therefore passes the LCYB rate directly to that model while leaving its product-specific equations and parameters unchanged.'),
      eq('Shared boundary', String.raw`v_{\mathrm{in,BCAR}}(t)=v_{\mathrm{LCYB}}(t)`),
      p('Numerical coupling uses the downstream Vmax, Km, loss constants and initial concentrations from that workstream. The shared boundary assigns each parameter to the measurements that define it.'),
    ),
  ],
};

export const protein: WikiPage = {
  title: 'Protein Engineering and Regulatory Design', eyebrow: 'Dry Lab / Protein', status: 'team-draft',
  intro: 'Our protein workflow has two connected tracks. We used structure-guided design to improve the LCYB enzyme at the entry to the β-carotene hub, and sequence/domain analysis to build testable models of how the candidate transcription factor DsTF2146 could regulate LCYB expression. Each calculation is presented at its appropriate evidence level: design hypothesis, computational filter or experiment-ready prediction.',
  sections: [
    section('Workflow at a glance',
      p('The enzyme and regulatory tracks address different control points in the same pathway. LCYB engineering asks whether substrate access and positioning can be improved. DsTF2146 engineering asks which domains are required for DNA recognition, nuclear localisation and regulatory control. Protein–DNA docking is used only as supporting structural evidence, not as a substitute for DNA-binding or transcription assays.'),
      p('The two tracks therefore use different molecular evidence while contributing to the same pathway-level design. In the enzyme track, the mature LCYB model, candidate cavity, lycopene placement, residue environment and short WT/F404Y trajectories are connected to a specific catalytic design question. In the regulatory track, sequence comparison defines the conserved CXC core, predicted NLS and nearby S208 site; those features guide the domain constructs and the designed DNA substrate used for structural inspection.'),
      customTable('Two protein-engineering tracks', ['Track', 'Core workflow', 'Current output', 'Required validation'], [
        ['LCYB catalysis', 'Mature-structure model → cavity detection → lycopene docking → residue hypotheses → FoldX → short MD', 'Prioritised mutations and a WT/F404Y pilot trajectory comparison', 'Expression, pigment conversion and enzyme activity'],
        ['DsTF2146 regulation', 'Sequence comparison → CXC-domain mapping → disorder/NLS/phosphosite prediction → truncation design → protein–DNA docking audit', 'Domain constructs, regulatory mutations and a corrected validation plan', 'EMSA, promoter reporter, localisation and protein-abundance assays'],
      ]),
      p('This structure keeps the ten individual substitutions in their proper role: they are follow-up probes inside a broader rational-design programme, rather than the central result by themselves.'),
    ),
    section('Track I — LCYB structure and design objective',
      p('The LCYB reference sequence contains 597 amino acids. The structural workflow uses the project-predicted mature region spanning residues 71–597 while retaining full-length residue numbers. The supplied PDB contains one 527-residue chain, from Gln71 to Ser597, so positions such as Y159, H259 and F404 can be traced directly between the sequence, model and mutation records.'),
      p('Because lycopene is an extended hydrophobic substrate, we focused on pocket occupancy, access-channel geometry, aromatic contacts, polar positioning and steric restriction. The aim was to generate mechanistic variants that remained structurally plausible, rather than to optimise a single docking score.'),
      p('The structure views below connect the full-length numbering convention to the local substrate environment. The overall model locates the candidate pocket in the mature LCYB structure; the closer views show the docked lycopene pose against the surrounding side chains and the channel-facing region. This visual inspection provides the structural context for the cavity screen and for testing conservative versus volume-changing substitutions.'),
      p('The pocket analysis was interpreted as a combination of cavity size, ligand placement and residue chemistry. Cavity 2 was selected from five CB-Dock2 candidates because its reported score and position supported focused inspection, while the larger cavity 1 and the compact high-scoring cavity 5 remained comparison sites. The subsequent mutation panel samples distinct chemical changes: Y159F and Y200F retain aromatic rings while removing hydroxyl groups; H259Q and H259N alter imidazole polarity; F404Y adjusts the aromatic gate; and M405L, M405W, F404A and M406A probe local hydrophobic volume. This design makes the structural comparisons interpretable by separating aromatic, polar and steric contributions.'),
      fig('lycopene-cyclase-structure-1', 'Overall structure of the mature LCYB model with docked lycopene highlighted in the candidate pocket.', 'Figure 1. Overall structural view of the mature LCYB model and the docked lycopene pose. The ligand placement is a computational model used to locate the candidate substrate pocket.'),
      fig('lycopene-cyclase-structure-2', 'Close-up view of docked lycopene and surrounding LCYB pocket residues.', 'Figure 2. Close-up of the candidate LCYB pocket, showing the docked lycopene pose and nearby protein side chains used to frame residue-level design hypotheses.'),
      fig('lycopene-cyclase-structure-3', 'Alternative close-up orientation of the LCYB pocket and docked lycopene.', 'Figure 3. Complementary view of the LCYB pocket and docked lycopene. The second orientation helps compare pocket occupancy, aromatic contacts and access-channel geometry.'),
      customTable('LCYB structure conventions', ['Item', 'Project convention'], [
        ['Full-length reference', '597 aa; numbering 1–597'],
        ['Mature structural model', 'Residues 71–597; one 527-aa chain'],
        ['Numbering used below', 'Original full-length residue numbers'],
        ['Evidence level', 'Structure-guided hypotheses pending biochemical validation'],
      ]),
    ),
    section('Pocket discovery, docking and candidate selection',
      p('CB-Dock2 identified five candidate cavities. Cavity 2 was selected for focused lycopene docking because its position and geometry were compatible with the proposed substrate-access region. Repeated local docking with an exhaustiveness value of 32 was then used to test reproducibility and to identify nearby residues for mutation.'),
      customTable('CB-Dock2 cavity screen', ['Cavity', 'Volume (Å³)', 'Reported score', 'Use in this project'], [
        ['C1', '3056', '−8.2', 'Large alternative cavity'],
        ['C2', '2128', '−9.8', 'Selected for focused docking and residue analysis'],
        ['C3', '838', '−7.9', 'Not prioritised'],
        ['C4', '634', '−8.9', 'Not prioritised'],
        ['C5', '619', '−9.7', 'Small high-scoring alternative'],
      ]),
      p('The resulting candidate set tests aromatic hydroxyl groups, imidazole-mediated polarity, the proposed aromatic gate and local hydrophobic volume. FoldX was used only to remove mutations with large predicted folding penalties; it does not predict lycopene conversion.'),
      p('The FoldX values separate conservative substitutions from larger pocket perturbations. Y159F (−0.664 kcal mol⁻¹), M405L (−0.327 kcal mol⁻¹) and F404Y (−0.155 kcal mol⁻¹) form the fold-compatible end of the screen. H259Q is approximately neutral (+0.007 kcal mol⁻¹), while H259N and Y200F carry mild predicted penalties. By contrast, M405W, F404A, M406A and Y322F have progressively larger positive values, consistent with increased structural risk when side-chain volume or the pocket-channel boundary is changed more substantially. The screen therefore supports retaining chemically distinct, structurally plausible candidates while deprioritising substitutions with larger predicted destabilisation.'),
      customTable('LCYB FoldX structural-tolerance screen', ['Candidate', 'Mean ΔΔG (kcal mol⁻¹)', 'Design interpretation'], [
        ['Y159F', '−0.664', 'Aromatic contact retained; hydroxyl removed; predicted fold-compatible'],
        ['M405L', '−0.327', 'Conservative hydrophobic-volume adjustment'],
        ['F404Y', '−0.155', 'Aromatic gate retained with an added hydroxyl'],
        ['H259Q', '+0.007', 'Imidazole replaced by an amide; approximately neutral'],
        ['H259N', '+0.268', 'Smaller polar replacement; mild predicted penalty'],
        ['Y200F', '+0.399', 'Aromatic contact retained; mild predicted penalty'],
        ['M405W', '+1.362', 'Larger aromatic side chain; moderate predicted risk'],
        ['F404A', '+2.007', 'Large reduction in gate volume; predicted destabilisation'],
        ['M406A', '+4.277', 'Large hydrophobic-volume loss; predicted destabilisation'],
        ['Y322F', '+4.759', 'Predicted destabilisation near the pocket–channel boundary'],
      ]),
    ),
    section('F404Y emerged as the first LCYB validation candidate',
      p('A repeated local-docking comparison placed F404Y first in the tested set, with a mean score of −10.790 ± 0.046 versus −10.473 ± 0.068 for WT. The numerical difference is small and remains inside a docking model; it is therefore used to prioritise F404Y, not to claim a measured affinity or catalytic improvement.'),
      p('The ranking was interpreted together with the structural-tolerance screen rather than in isolation. F404Y preserves the aromatic gate while adding a hydroxyl group, and its repeated docking result is separated from WT by a modest score difference. M405L remains a conservative alternative, while the combined F404Y/M405L result does not show a clear additive advantage. The single-mutant comparison therefore defines a focused experimental candidate set without treating a docking score as an activity measurement.'),
      customTable('Repeated docking used for prioritisation', ['Candidate', 'Mean score ± SD', 'Difference from WT', 'Decision'], [
        ['F404Y', '−10.790 ± 0.046', '−0.317', 'First candidate for MD and experiment'],
        ['M405L', '−10.577 ± 0.093', '−0.103', 'Retain as a conservative alternative'],
        ['F404Y/M405L', '−10.560 ± 0.106', '−0.087', 'No clear additivity in this screen'],
        ['Y200F', '−10.480 ± 0.142', '−0.007', 'Indistinguishable from WT at this resolution'],
        ['WT', '−10.473 ± 0.068', '0', 'Reference'],
        ['Y159F', '−10.397 ± 0.061', '+0.077', 'Fold-compatible but no docking advantage'],
        ['H259Q', '−10.200 ± 0.090', '+0.273', 'Lower priority in this docking setup'],
      ]),
    ),
    section('WT and F404Y: completed 5 ns pilot MD',
      p('Both WT and F404Y simulations completed 5 ns. To reduce the influence of initial relaxation, the values below summarise the final 4 ns. Temperature and density were stable in both systems, supporting basic run integrity. F404Y showed a slightly lower mean Cα RMSF and a slightly more compact radius of gyration, but its ligand RMSD was higher than WT. Contact counts and minimum protein–ligand distances were very similar.'),
      p('The trajectory comparison gives a balanced account of the variant. Global backbone deviation, close-contact distance and contact count remain closely matched between WT and F404Y. The modestly lower RMSF and radius of gyration for F404Y occur alongside a higher ligand RMSD, so the trajectories support compatibility of the modeled substitution while keeping ligand mobility visible as a separate measure. Temperature and density remain closely matched throughout the complete runs.'),
      customTable('GROMACS pilot trajectory summary; final 4 ns unless stated', ['Metric', 'WT', 'F404Y', 'Interpretation'], [
        ['Protein backbone RMSD (nm)', '0.140 ± 0.010', '0.145 ± 0.011', 'Very similar global backbone deviation'],
        ['Ligand RMSD after protein fit (nm)', '0.179 ± 0.026', '0.208 ± 0.020', 'F404Y does not show lower ligand mobility in this short run'],
        ['Protein radius of gyration (nm)', '2.370 ± 0.007', '2.363 ± 0.006', 'F404Y is marginally more compact'],
        ['Minimum protein–ligand distance (nm)', '0.202 ± 0.012', '0.197 ± 0.013', 'Comparable close contact'],
        ['Contacts within 0.45 nm', '93.48 ± 1.76', '94.23 ± 1.55', 'Nearly identical contact counts'],
        ['Mean Cα RMSF over residues (nm; full 5 ns)', '0.081 ± 0.049', '0.074 ± 0.038', 'Slightly lower average fluctuation for F404Y'],
        ['Temperature (K; full 5 ns)', '299.93 ± 1.12', '300.03 ± 1.15', 'Both simulations remained near 300 K'],
        ['Density (kg m⁻³; full 5 ns)', '1025.16 ± 1.99', '1027.28 ± 1.93', 'Stable and closely matched systems'],
      ]),
      p('Taken together, the paired trajectories show that F404Y remains structurally compatible with the modeled LCYB–ligand system over the simulated interval. The matched temperature, density, backbone deviation, close-contact distance and contact counts provide a direct WT comparison, while the higher ligand RMSD for F404Y keeps ligand mobility distinct from the modest changes in compactness and average fluctuation. These results define the structural profile of the first design candidate for comparison with enzyme-expression, pigment-conversion and activity measurements.'),
    ),
    section('Track II — DsTF2146 sequence and domain architecture',
      p('Candidate_2146 is a 457-aa CPP/CXC-family transcription-factor candidate. Comparison with the 550/551-aa reference shows 55.8% global identity, but 85.0% identity when alignment gaps are excluded and 96% identity across the conserved N-terminal region. Most length differences occur in low-complexity, predicted-disordered middle and C-terminal segments.'),
      p('The sequence comparison separates a compact, conserved N-terminal functional region from length variation concentrated in predicted flexible segments. Within Candidate_2146, CXC1 spans approximately residues 37–68 and CXC2 approximately 122–154; both contain nine conserved cysteines. The NLS motif PPHKRARTA lies at residues 209–217, immediately after S208, while the predicted disordered regions are concentrated in the middle and C terminus. These features organize the construct design around a dual-CXC core, a localisation motif and regulatory sequence context.'),
      p('The alignment statistics are useful at two scales: global identity is 55.8%, whereas identity rises to 85.0% when alignment gaps are excluded and to 96% across the conserved N-terminal region. The difference reflects length variation in low-complexity segments rather than uniform divergence of the conserved core. The CXC1–CXC2 interval reaches approximately 98.2% identity to the reference, making it the clearest sequence-supported region for defining shared domain constructs. S208 and the immediately adjacent basic NLS form a separate local design unit whose contribution can be tested without conflating it with the distal disordered regions.'),
      p('The structural views below show the modeled CXC-containing protein at complementary scales. Together with the sequence alignment, they provide a visual map for locating the conserved domain core and for comparing the truncation designs; they are structural illustrations of the computational models used in the design workflow.'),
      fig('cxc-domain-structure-4', 'Structural model of the Candidate_2146 CXC-containing region used to frame domain and residue-level designs.', 'Figure 4. Structural view of the Candidate_2146 model used to frame the CXC-domain design. The highlighted protein region provides structural context for the sequence-conserved domain and planned constructs.'),
      customTable('Sequence-derived architecture', ['Feature', 'Project result', 'Interpretation'], [
        ['CXC1 domain', 'Approximately residues 37–68; nine conserved cysteines', 'Strongly conserved candidate DNA/metal-associated domain'],
        ['CXC2 domain', 'Approximately residues 122–154; nine conserved cysteines', 'Second conserved CXC domain'],
        ['CXC1–CXC2 region', 'Approximately 98.2% identity to the reference', 'Highest-confidence conserved functional core'],
        ['Predicted NLS', 'Residues 209–217: PPHKRARTA', 'Testable nuclear-localisation hypothesis'],
        ['Nearby phosphosite', 'S208, immediately before the predicted NLS', 'Possible coupling between phosphorylation and localisation'],
        ['Predicted disordered regions', '259–321, 350–379 and 415–450; broader flexibility near 177–222', 'Candidate regulatory regions and interaction motifs'],
      ]),
      p('Conserved cysteines support a CXC-family assignment, but they do not by themselves prove zinc coordination, DNA-binding specificity or transcriptional function. Metal binding and domain folding require direct structural or biochemical validation.'),
    ),
    section('Truncation and mutation design for DsTF2146',
      p('The domain analysis supports a staged construct strategy. A key naming correction is required: the previously labelled “CXC1–NLS truncation” spanning residues 21–230 contains both CXC1 and CXC2, as well as S208 and the predicted NLS. It should be described as a dual-CXC core/NLS construct, not as CXC1 alone.'),
      p('This boundary correction makes the construct panel biologically interpretable. Residues 21–230 retain both conserved CXC domains together with S208 and the NLS, so this construct tests the combined core rather than CXC1 in isolation. The CXC1-only and CXC2-only constructs then resolve the contribution of each module, while full-length WT supplies the reference context. Y48F and Y133F probe conserved aromatic positions in the two CXC regions; K212Q and K212Q/R213Q progressively alter the NLS charge pattern; and the phosphosite cluster variants explore the sequence immediately upstream of the localisation motif.'),
      p('The construct comparison is organised to distinguish domain content from regulatory sequence effects. Full-length WT anchors the reference phenotype; residues 21–230 retain both CXC domains and the S208–NLS region; isolated CXC1 and CXC2 constructs resolve the individual domain contributions. The point-mutant panel then changes one feature at a time where possible: aromatic-ring chemistry at Y48/Y133, local NLS charge at K212, and the S208 phosphosite state. The staged design allows localisation, protein abundance and DNA-binding readouts to be interpreted against the exact sequence change represented in each construct.'),
      customTable('Recommended construct logic', ['Construct or variant', 'Content', 'Question tested', 'Priority'], [
        ['Full-length WT', 'Residues 1–457', 'Reference localisation, DNA binding and transcription', 'Essential control'],
        ['Dual-CXC core/NLS', 'Residues 21–230; contains CXC1, CXC2, S208 and NLS', 'Whether the conserved core is sufficient for localisation and binding', 'High'],
        ['CXC1-only', 'Minimal CXC1 construct', 'Contribution of the first CXC domain', 'Mechanistic'],
        ['CXC2-only', 'Approximately residues 117–158', 'Contribution of the second CXC domain', 'Mechanistic'],
        ['ΔNLS / S208A / S208D', 'Localisation and phosphosite controls', 'Whether S208 and the basic motif regulate nuclear entry', 'High'],
        ['Y48F and Y133F', 'One aromatic substitution in each conserved CXC region', 'Test aromatic contributions without removing the ring', 'First mutation batch'],
        ['K212Q', 'Single change inside the predicted NLS', 'Test local charge while retaining an interpretable single-site design', 'First mutation batch with localisation control'],
        ['K212Q/R213Q', 'Double NLS charge change', 'Stronger localisation perturbation', 'Second batch'],
        ['4A / 4E near 198–201', 'Non-phosphorylatable / phosphomimetic clusters', 'Exploratory phosphorylation-state model', '4A after redesign; 4E not first-line'],
      ]),
    ),
    section('DNA substrate selection and docking quality control',
      p('No clear CPP-family motif was identified in the scanned LCYB promoter sequence. The main 25-bp docking duplex was therefore designed from the Arabidopsis TSO1 JASPAR motif rather than demonstrated as a native LCYB promoter site. This makes the docking a transferable structural hypothesis, not proof that DsTF2146 binds the LCYB promoter in vivo.'),
      p('The sequence logo records the designed 15-position motif used to define the recognition pattern for the DNA substrate. The motif-derived sequence was assembled into the 25-bp duplex for docking, keeping the design substrate explicit and distinguishable from a native LCYB promoter segment. This provides a consistent sequence reference for interpreting the structural illustration and for tracking the DNA design through the docking workflow.'),
      fig('dna-logo', 'Sequence logo of the 15-position designed DNA motif used to construct the docking duplex.', 'Figure 5. Sequence logo of the designed DNA motif used to construct the 25-bp docking duplex. The motif was derived from the Arabidopsis TSO1 JASPAR motif and is distinct from a validated native LCYB promoter site.'),
      p('The docking models also did not converge to a dominant cluster: reported ligand RMSDs were above 50 Å. Several mutants produced identical scores and coordinates, and a repaired full-length complex contained a severe Gln362–DNA steric collision. Under these conditions, docking-score differences cannot be interpreted as affinity changes, and they cannot be converted into predicted transcription strength.'),
      p('These quality checks define how the calculated poses and scores are used in the project. RMSD values above 50 Å indicate that the sampled ligand placements are widely separated rather than forming a common pose family. Identical coordinates and scores across some mutant entries are treated as a model-generation or input-audit signal, not as independent evidence that the proteins bind identically. The Gln362–DNA overlap identifies a concrete steric incompatibility in the repaired full-length model. Together, these observations distinguish the role of docking as a way to visualise candidate interfaces from quantitative binding evidence.'),
      p('The docking illustration pairs the designed DNA with the mutated protein model to show the intended components of the structural setup. It should be read together with the sequence logo: the logo defines the designed DNA pattern, while the structure view shows that DNA sequence represented in a protein–DNA docking model. The pose is presented as the project’s computational design visualization, not as a measured binding geometry.'),
      fig('protein-dna-docking', 'Docking illustration showing the designed DNA sequence paired with a mutated Candidate_2146 protein model.', 'Figure 6. Protein–DNA docking illustration pairing the designed DNA with a mutated Candidate_2146 protein model. The image visualises the designed sequence and modeled protein together in the docking workflow.'),
      customTable('Protein–DNA docking: what the current results mean', ['Observation', 'Supported conclusion', 'Unsupported conclusion'], [
        ['Designed 25-bp motif-derived duplex', 'A controlled substrate for testing a CPP/CXC binding hypothesis', 'A validated native LCYB promoter site'],
        ['Docking scores for truncations and mutants', 'Starting poses for interface inspection and experimental prioritisation', 'Binding constants, kcal mol⁻¹ values or transcriptional output'],
        ['Ligand RMSD > 50 Å and no dominant cluster', 'Docking uncertainty is high and poses are not directly comparable', 'A reliable affinity ranking'],
        ['Identical values for several mutant models', 'Inputs and structure generation must be audited', 'Evidence that the mutants behave identically'],
        ['Full-length clash near Gln362', 'The pose requires redocking or restrained relaxation before interface scoring', 'A favourable DNA contact'],
      ]),
      p('Together, the sequence logo, docking audit and construct design form a coherent protein–DNA work package. The logo specifies the designed substrate; the docking models place that sequence alongside full-length or domain-level protein structures; and the pose checks identify which structural comparisons are interpretable. The project can therefore connect a defined DNA input to explicit construct choices and to the EMSA, promoter-reporter and localisation measurements listed in the validation plan.'),
    ),
    section('Engineering conclusions and next cycle',
      h('What the current work supports'),
      p('For LCYB, the workflow links cavity selection, substrate-pose inspection, residue-level hypotheses, structural-tolerance filtering and a completed WT/F404Y pilot MD comparison. F404Y is the first prioritised variant because its modeled pocket interactions and trajectory profile make it a clear design candidate for the enzyme track. For DsTF2146, sequence comparison identifies a conserved dual-CXC architecture, while the corrected 21–230 construct definition connects both CXC domains with S208 and the predicted NLS. The DNA-design and docking audit then place the regulatory constructs in a defined sequence and structural context.'),
      h('Planned design–build–test–learn sequence'),
      customTable('Recommended validation order', ['Priority', 'Action', 'Decision enabled'], [
        ['1', 'Experimentally compare WT LCYB and F404Y; retain M405L as an independent conservative candidate', 'Whether computational prioritisation improves lycopene conversion'],
        ['2', 'Run longer replicate MD only for variants that remain experimentally relevant', 'Whether structural trends reproduce across trajectories'],
        ['3', 'Test DsTF2146 full length, dual-CXC core/NLS, CXC1-only, CXC2-only and ΔNLS constructs', 'Which regions are required for localisation and DNA binding'],
        ['4', 'Validate the LCYB promoter binding site by motif scan plus EMSA/footprinting before affinity engineering', 'Whether the designed duplex represents a biologically relevant site'],
        ['5', 'Test Y48F, Y133F and K212Q with localisation and expression controls', 'Whether aromatic residues or NLS charge tune regulatory behaviour'],
        ['6', 'Feed measured enzyme activity, binding and reporter data back into the next modelling round', 'Closed-loop model refinement'],
      ]),
    ),
  ],
};

export const dryLabIndex: WikiPage = {
  title: 'Dry Lab', eyebrow: 'Project / Dry Lab', intro: '', status: 'team-draft',
  sections: [section('Chapters', links(...dryLabNavigation.map(([label, href]): [string,string] => [label,href])))],
};

export const emptyDryLabPage = (title: string): WikiPage => ({ title, eyebrow: `Dry Lab / ${title}`, intro: '', status: 'structure-only', sections: [] });
